name = "r2_performance_test"
main = "src/index.ts"
compatibility_date = "2023-01-21"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "performance-test"
preview_bucket_name = "preview-performance-test"